### ISSUE TITLE
[edge case] create a pvc, delete the pv, delete the pvc, volume isn’t deleted

### ISSUE THREAD

**Issue by clanstyles** [packethost/csi-packet#53]
If you create a full StatefulSet/Deployment with a PV/PVC and manually remove them in the following order:

1. Statefulset/Deployment
2. PV
3. PVC

It wont delete the actual PV from Packet.

Quick way to reproduce on the test cluster:

```
kubectl apply -f /root/csi-packet-master.bk/deploy/mysql-deployment.yaml
kubectl apply -f /root/csi-packet-master.bk/deploy/mysql-pass-cfg.yaml

kubectl delete deployment/wordpress-mysql
kubectl delete pv/...
kubectl delete pvc/...
```

**Comment by deitch** [comment]
Hi @clanstyles . I replicated this via the following:

1. Create a `pvc`
1. Watch it create the `pv`
1. Try to delete the `pv` (while it is still bound to the `pvc`)
1. It waits for the `pvc` to free up, which is as it should based on [storage in use protection](https://v1-12.docs.kubernetes.io/docs/tasks/administer-cluster/storage-object-in-use-protection/)
1. Delete the `pvc`
1. The `pv` automatically gets deleted
1. The `DeleteVolume` on the driver never is called - **this is the bug**

However, I think this is a CSI issue. I will raise it there.

**Comment by deitch** [comment]
Confirmed, this issue is a problem with the [csi provisioner](https://github.com/kubernetes-csi/external-provisioner) and not the Packet driver. You can follow the open issue [here](https://github.com/kubernetes-csi/external-provisioner/issues/195), which I am going to comment on.

In any case, I am going to close this, as it is not a Packet driver issue.
